# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injection_test.Task'),
        ),
    ]
