# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0002_auto_20160725_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='IObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_url', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='IParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('i_value', models.CharField(max_length=32)),
                ('i_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_parameter', to='injection_test.IObject')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='page',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iobject',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_object', to='injection_test.Task'),
        ),
    ]
