# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0003_auto_20160725_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iobject',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_objects', to='injection_test.Task'),
        ),
        migrations.AlterField(
            model_name='iparameter',
            name='i_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_parameters', to='injection_test.IObject'),
        ),
    ]
