# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0004_auto_20160725_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='iobject',
            name='i_method',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
