# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0006_auto_20160726_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('task', models.ManyToManyField(related_name='policies', to='injection_test.Task')),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='task',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
