# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0007_auto_20160727_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='policies', to='injection_test.Task'),
        ),
    ]
