# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0008_auto_20160727_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='add_url',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
