# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection_test', '0009_policy_add_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='iobject',
            name='add_url',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
